Script started on Tue Apr 30 13:30:07 2019
]0;sa1998@klaatu:~[?1034h[sa1998@klaatu ~]$ gcc -g -o gasp gasp.c
]0;sa1998@klaatu:~[sa1998@klaatu ~]$ gdb ./gasp
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-36.el7
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./gasp...done.
(gdb) b main
Breakpoint 1 at 0x400826: file gasp.c, line 21.
(gdb) b 54
Breakpoint 2 at 0x40095f: file gasp.c, line 54.
(gdb) r -n GoHuskies problem1
Starting program: /homes/sa1998/gasp -n GoHuskies problem1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64

Breakpoint 1, main (argc=4, argv=0x7fffffffdf48) at gasp.c:21
21	  if (argc < 3) {
(gdb) p argv[2]
$1 = 0x7fffffffe21f "GoHuskies"
(gdb) c
Continuing.

Breakpoint 2, openFile (fileIndex=3, argv=0x7fffffffdf48, i=0, n=1) at gasp.c:54
54	  if (file == NULL) {
(gdb) by t
#0  openFile (fileIndex=3, argv=0x7fffffffdf48, i=0, n=1) at gasp.c:54
#1  0x00000000004008f9 in main (argc=4, argv=0x7fffffffdf48) at gasp.c:40
(gdb) list
49	  // open the file
50	  FILE* file = fopen(argv[fileIndex], "r"); //pointer to the file
51	 
52	  // check if the file exists
53	  // if not then output a message with file otherwise continue matching patter to file
54	  if (file == NULL) {
55	    fprintf(stderr, "File: %s does not exsist.\n", argv[fileIndex]);
56	  } else {
57	    char line[MAX_LINE];
58	    int lineNumber = 0;
(gdb) p argv[fileIndex]
$2 = 0x7fffffffe229 "problem1"
(gdb) p file
$3 = (FILE *) 0x603010
(gdb) c
Continuing.
problem1: 7: echo GoHuskies
problem1: 9: # the former command puts the text 'GoHuskies' in the file GoHuskies and then
problem1: 10: # the latter command prints the text inside the file GoHuskies
problem1: 11: echo GoHuskies > GoHuskies
problem1: 12: cat GoHuskies
problem1: 15: ls GoHuskies
problem1: 17: # we alrady saved the word 'GoHuskies' in the file GoHuskies
problem1: 18: # grep command is finding the pattern 'GoHuskies' in the file GoHuskies and then prints it
problem1: 19: grep 'GoHuskies' GoHuskies
problem1: 21: # created an alias named GoHuskies which prints out nothing and then called the alias
problem1: 23: alias GoHuskies=''
problem1: 24: GoHuskies
[Inferior 1 (process 19186) exited normally]
(gdb) quit
]0;sa1998@klaatu:~[sa1998@klaatu ~]$ exit
exit

Script done on Tue Apr 30 13:35:43 2019
